<?php
/**
 * Editor-script asset manifest for the reader-chat block.
 *
 * Normally generated by @wordpress/scripts at build time alongside the
 * compiled JS. Since this plugin is build-step-free, the manifest is
 * hand-maintained: it lists the wp.* packages the IIFE references via
 * globals so WordPress enqueues them before edit.js runs.
 *
 * Adding a new wp.something.X reference in edit.js? Add wp-something
 * here too.
 */

return array(
	'dependencies' => array(
		'wp-blocks',
		'wp-element',
		'wp-block-editor',
		'wp-components',
		'wp-i18n',
	),
	'version'      => '0.2.1',
);
